# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='', help_text="Enter the book's natural language (e.g. English, Spanish, French)", max_length=200),
            preserve_default=False,
        ),
    ]
